2023-09-23 13:13:52,232 ERROR Internal Server Error: /post/ C:\Users\skropotin\PycharmProjects\BreakingNews\venv\lib\site-packages\django\utils\log.py (<class 'AttributeError'>, AttributeError("'super' object has no attribute 'get_queryse'"), <traceback object at 0x0000026A8BE7DBC0>)
Traceback (most recent call last):
  File "C:\Users\skropotin\PycharmProjects\BreakingNews\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\skropotin\PycharmProjects\BreakingNews\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\skropotin\PycharmProjects\BreakingNews\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\skropotin\PycharmProjects\BreakingNews\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\skropotin\PycharmProjects\BreakingNews\venv\lib\site-packages\django\views\generic\list.py", line 154, in get
    self.object_list = self.get_queryset()
  File "C:\Users\skropotin\PycharmProjects\BreakingNews\NewsPaper\News\views.py", line 23, in get_queryset
    queryset = super().get_queryse()
AttributeError: 'super' object has no attribute 'get_queryse'
2023-09-23 13:13:52,359 ERROR "GET /post/ HTTP/1.1" 500 145 C:\Users\skropotin\PycharmProjects\BreakingNews\venv\lib\site-packages\django\core\servers\basehttp.py None
2023-09-23 13:14:21,389 ERROR Internal Server Error: /post/ C:\Users\skropotin\PycharmProjects\BreakingNews\venv\lib\site-packages\django\utils\log.py (<class 'AttributeError'>, AttributeError("'super' object has no attribute 'get_queryse'"), <traceback object at 0x0000026A8C276FC0>)
Traceback (most recent call last):
  File "C:\Users\skropotin\PycharmProjects\BreakingNews\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\skropotin\PycharmProjects\BreakingNews\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\skropotin\PycharmProjects\BreakingNews\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\skropotin\PycharmProjects\BreakingNews\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\skropotin\PycharmProjects\BreakingNews\venv\lib\site-packages\django\views\generic\list.py", line 154, in get
    self.object_list = self.get_queryset()
  File "C:\Users\skropotin\PycharmProjects\BreakingNews\NewsPaper\News\views.py", line 23, in get_queryset
    queryset = super().get_queryset()
AttributeError: 'super' object has no attribute 'get_queryse'
2023-09-23 13:14:21,555 ERROR "GET /post/ HTTP/1.1" 500 145 C:\Users\skropotin\PycharmProjects\BreakingNews\venv\lib\site-packages\django\core\servers\basehttp.py None
2023-09-23 13:38:13,455 ERROR Internal Server Error: /post/4/update/ C:\Users\skropotin\PycharmProjects\BreakingNews\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('flatpages/post_updates.html'), <traceback object at 0x000002D98A372340>)
Traceback (most recent call last):
  File "C:\Users\skropotin\PycharmProjects\BreakingNews\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\skropotin\PycharmProjects\BreakingNews\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\skropotin\PycharmProjects\BreakingNews\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\skropotin\PycharmProjects\BreakingNews\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\skropotin\PycharmProjects\BreakingNews\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\skropotin\PycharmProjects\BreakingNews\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: flatpages/post_updates.html
2023-09-23 13:38:13,523 ERROR "GET /post/4/update/ HTTP/1.1" 500 145 C:\Users\skropotin\PycharmProjects\BreakingNews\venv\lib\site-packages\django\core\servers\basehttp.py None
